typography_spectrum: 0.3640747421886772
color:
  brandStrength: 0.48844090406782925
  lightness: 0.5064873634837568
  saturation: 0.05865479772910476
  rhythmicContrast: 0.6851280126720667
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
layout_spectrum: 0.33113516168668866
name: SNUGGLER
style: the-composer
navigation:
  - name: Illustration
    id: cbf7ecde-94fe-4c29-8f9e-9fa076d5a4e9
    type: content
  - name: test
    id: 4d639d39-eee0-4948-8f5c-ac34f69af091
    type: content
  - name: This is the most amazing drone we've seen yet
    id: d3e4dba3-17a8-4786-8aee-e17b3efbcc4c
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/be44cf55-ed41-4ffd-824c-bd40e69f0371.jpg
title: SNUGGLE YOU BACK TO HEALTH
